fast_bert/lm-data.py
[flake8](http://flake8.pycqa.org) testing of https://github.com/kaushaltrivedi/fast-bert on Python 3.7.1
$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./container/bert/predictor.py:96:34: F821 undefined name 'searching_all_files'
file_list.append(searching_all_files(x))
^
./fast_bert/lm-data.py:217:12: F821 undefined name 'random'
if random.random() > 0.5:
^
./fast_bert/lm-data.py:278:32: F821 undefined name 'random'
rand_doc_idx = random.randint(0, len(self.all_docs)-1)
^
./fast_bert/lm-data.py:280:33: F821 undefined name 'random'
line = rand_doc[random.randrange(len(rand_doc))]
^
./fast_bert/lm-data.py:282:30: F821 undefined name 'random'
rand_index = random.randint(
^
./fast_bert/lm-data.py:324:27: F821 undefined name 'random_word'
t1_random, t1_label = …
```
=> Undefined names: import logger, random

fast_bert/metrics.py
Hamming loss, exact match ratio, as well as F1 based on fbeta
=> Additional metrics for multi-label classification

fast_bert/learner_cls.py, setup.py
LAMB optimiser has been set as default optimiser.  This allows BERT to be trained much faster
=> LAMB optimizer added

fast_bert/learner.py
Indentation issue was there due to Empty Learner class
=> fixed ConstantLR not defined and Indentation issue

fast_bert/data_cls.py
- Fixed issue which prevented the `no_cache` parameter from `DataBunch `to take effect
The BertDataBunch class was accepting the `no_cache` paramter but it had no effect.
I have added the parameter into the the conditional to that handles if get train examples or not (to load them from cache)
```
if os.path.exists(cached_features_file) == False or self.no_cache == True
```
I have added the parameter into the call to the `get_dataset_from_examples `function which was expecting it.
```
train_dataset = self.get_dataset_from_examples(train_examples, 'train', no_cache=self.no_cache)
```
- Modified the cache file name management to allow having several datasets on same folder and still use cache correctly
=> Modified cache management

fast_bert/data_lm.py, fast_bert/learner_lm.py
=> Fix incorrect reference to RobertaTokenizer.add_special_tokens_single_sequence()

fast_bert/data_cls.py, fast_bert/data_lm.py, fast_bert/data_qa.py
Saving the ```BertDataBunch``` class is crucial to have especially given how long it takes to process text during its instantiation.
=> Add save method to BertDataBunch classes to resolve issue: #109

container/bert/predictor.py
=> Fix deployment on SageMaker in `predict.py`

fast_bert/data_lm.py, fast_bert/learner_lm.py
transformers.tokenizer replace from add_special_tokens_single_sequence to build_inputs_with_special_tokens
https://github.com/huggingface/transformers/commit/6c1d0bc0665ef01710db301fb1a0a3c23778714a
=> fix for https://github.com/kaushaltrivedi/fast-bert/issues/85

.flake8, .vscode/settings.json, fast_bert/__init__.py, fast_bert/data_abs.py, fast_bert/data_cls.py, fast_bert/learner_abs.py, fast_bert/learner_cls.py, fast_bert/summarisation/__init__.py, fast_bert/summarisation/configuration_bertabs.py, fast_bert/summarisation/modeling_bertabs.py, requirements.txt, setup.py, test/summarisation.ipynb
=> Abs summarisation

container/Dockerfile_gpu
I had been hitting errors trying to use python and pip otherwise. Also the dockerfile was missing some pip packages needed.
=> Install python using miniconda

fast_bert/modeling.py
Enables albert models to train/predict, addresses #172 and #184
=> Corrected model reference for albert models

fast_bert/learner_cls.py
allows one to freeze all model parameters with a name starting with the data.model_type
=> added freeze_transformer_layers optional parameter

.vscode/settings.json, container/Dockerfile_gpu, container/bert/predictor.py, container/bert/train, fast_bert/data_cls.py, fast_bert/learner_cls.py, fast_bert/prediction.py, requirements.txt, setup.py
Switch to auto-model for multi-class classification
=> Auto model

container/Dockerfile_gpu, container/build_and_push.sh
fix for when download of miniconda fails in docker image build
=> fixes for Dockerfile_gpu build

fast_bert/data.py, fast_bert/data_cls.py, fast_bert/data_qa.py
Allows one to pass a custom sampler to the training DataLoader. For example, one can now pass a WeightedRandomSampler to implement oversampling on underrepresented classes.
=> parameterized custom sampler to allow weighted sampling

fast_bert/data_cls.py
Casted row of label column to string to allow for integer labels.
=> Multilabel integer labels

README.md, fast_bert/prediction.py
Hi :)
This allows using custom torch devices to predict using a saved model.
=> Allow setting custom device in prediction.py

fast_bert/learner_cls.py
fixes pos_weight and weight does not exist exception
=> Fixed missing function argument for pos_weight variable

container/Dockerfile
Updates cryptography, removes gevent to improve container security
=> Improve container security

container/Dockerfile
updates cryptography to remove container vulnerability
=> Adds update to cryptography

fast_bert/learner_util.py, requirements.txt, setup.py
- bump transformers library to 4.18.0
- update setup
- update lamb optimiser parameters
=> upgrade to transformers version 4.0
